"""create initial tables

Revision ID: 2ca8972639d9
Revises: 
Create Date: 2026-09-05 16:57:06.874863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ca8972639d9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('owner_name', sa.String(length=100), nullable=False, comment='Full name of the MSME owner'),
    sa.Column('business_name', sa.String(length=200), nullable=False, comment='Registered business name'),
    sa.Column('gstin', sa.String(length=15), nullable=False, comment='15-character GST Identification Number — primary business identifier'),
    sa.Column('phone', sa.String(length=15), nullable=False, comment='Mobile number for RCS/SMS/voice alerts'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='Email address — optional'),
    sa.Column('preferred_channel', sa.String(length=20), nullable=False, comment='Primary delivery channel: rcs, sms, voice, telegram'),
    sa.Column('telegram_chat_id', sa.Integer(), nullable=True, comment='Telegram chat ID — populated only for Option A customers'),
    sa.Column('preferred_language', sa.String(length=5), nullable=False, comment='Alert language: kn=Kannada, hi=Hindi, en=English'),
    sa.Column('cluster', sa.String(length=100), nullable=True, comment='Industrial cluster location for price benchmarking'),
    sa.Column('udyam_number', sa.String(length=30), nullable=True, comment='Udyam Registration Number for GeM eligibility'),
    sa.Column('turnover_band', sa.String(length=20), nullable=True, comment='Annual turnover band for scheme eligibility'),
    sa.Column('product_categories', sa.Text(), nullable=True, comment='Comma-separated product categories for GeM matching'),
    sa.Column('ca_id', sa.Uuid(), nullable=True, comment='ID of the CA who enrolled this customer — for revenue sharing'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether this customer is actively receiving alerts'),
    sa.Column('is_trial', sa.Boolean(), nullable=False, comment='Whether customer is in trial — no fees charged during trial'),
    sa.Column('trial_ended_at', sa.DateTime(timezone=True), nullable=True, comment='When the trial period ended — NULL if still in trial'),
    sa.Column('onboarded_at', sa.DateTime(timezone=True), nullable=True, comment='When onboarding was fully completed'),
    sa.Column('gstn_username_encrypted', sa.Text(), nullable=True, comment='Fernet-encrypted GSTN portal username'),
    sa.Column('gstn_password_encrypted', sa.Text(), nullable=True, comment='Fernet-encrypted GSTN portal password'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_cluster'), 'customers', ['cluster'], unique=False)
    op.create_index(op.f('ix_customers_gstin'), 'customers', ['gstin'], unique=True)
    op.create_table('itc_tracking',
    sa.Column('customer_id', sa.Uuid(), nullable=False, comment='Which customer this ITC summary belongs to'),
    sa.Column('tax_period', sa.String(length=6), nullable=False, comment='GST tax period: MMYYYY format e.g. 082026 for August 2026'),
    sa.Column('period_display', sa.String(length=20), nullable=False, comment='Human readable period name e.g. August 2026'),
    sa.Column('eligible_itc', sa.Numeric(precision=14, scale=2), nullable=False, comment='Total ITC eligible for this period from all purchases'),
    sa.Column('matched_itc', sa.Numeric(precision=14, scale=2), nullable=False, comment='ITC amount that appeared in GSTR-2B — safe to claim'),
    sa.Column('at_risk_itc', sa.Numeric(precision=14, scale=2), nullable=False, comment='ITC not yet in GSTR-2B — at risk of being lost'),
    sa.Column('recovered_itc', sa.Numeric(precision=14, scale=2), nullable=False, comment='ITC recovered this period that was previously at risk'),
    sa.Column('missing_invoice_count', sa.Integer(), nullable=False, comment='Number of invoices not yet in GSTR-2B'),
    sa.Column('fee_rate', sa.Numeric(precision=4, scale=2), nullable=False, comment='Fee rate applied: 0.20 = 20% of recovered ITC'),
    sa.Column('fee_amount', sa.Numeric(precision=14, scale=2), nullable=False, comment='Fee charged = recovered_itc × fee_rate'),
    sa.Column('fee_invoiced', sa.Boolean(), nullable=False, comment='Whether fee invoice has been sent to customer'),
    sa.Column('fee_paid', sa.Boolean(), nullable=False, comment='Whether customer has paid the fee'),
    sa.Column('reconciliation_status', sa.String(length=20), nullable=False, comment='Status: pending, running, completed, failed, alerted'),
    sa.Column('last_reconciled_at', sa.String(length=30), nullable=True, comment='ISO datetime of last reconciliation run'),
    sa.Column('alert_sent_at', sa.String(length=30), nullable=True, comment='ISO datetime when alert was sent to customer'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error details if reconciliation_status is failed'),
    sa.Column('gstr2b_raw_response', sa.Text(), nullable=True, comment='Raw GSTR-2B API response stored for audit and debugging'),
    sa.Column('ca_share_amount', sa.Numeric(precision=14, scale=2), nullable=False, comment='CA revenue share amount = fee_amount × 0.20'),
    sa.Column('ca_share_paid', sa.Boolean(), nullable=False, comment='Whether CA revenue share has been paid'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_itc_status', 'itc_tracking', ['reconciliation_status'], unique=False)
    op.create_index(op.f('ix_itc_tracking_customer_id'), 'itc_tracking', ['customer_id'], unique=False)
    op.create_index('uq_itc_customer_period', 'itc_tracking', ['customer_id', 'tax_period'], unique=True)
    op.create_table('purchases',
    sa.Column('customer_id', sa.Uuid(), nullable=False, comment='Which customer made this purchase'),
    sa.Column('supplier_gstin', sa.String(length=15), nullable=False, comment="Supplier's GSTIN — used for GSTR-2B matching"),
    sa.Column('supplier_name', sa.String(length=200), nullable=False, comment='Supplier business name — for readable alerts'),
    sa.Column('supplier_phone', sa.String(length=15), nullable=True, comment='Supplier phone for automated delivery follow-up'),
    sa.Column('invoice_number', sa.String(length=50), nullable=False, comment="Invoice number as printed on the supplier's invoice"),
    sa.Column('invoice_date', sa.String(length=10), nullable=False, comment='Invoice date in YYYY-MM-DD format'),
    sa.Column('tax_period', sa.String(length=6), nullable=False, comment='GST tax period in MMYYYY format e.g. 082026'),
    sa.Column('material_name', sa.String(length=200), nullable=False, comment='Name of material purchased — used for price benchmarking'),
    sa.Column('material_grade', sa.String(length=100), nullable=True, comment='Material grade/specification for accurate price comparison'),
    sa.Column('hsn_code', sa.String(length=8), nullable=True, comment='HSN code for GST classification and rate verification'),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False, comment='Quantity purchased'),
    sa.Column('unit', sa.String(length=10), nullable=False, comment='Unit of measurement: kg, nos, mtr, ltr etc'),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False, comment='Price per unit before GST — used for benchmarking'),
    sa.Column('taxable_value', sa.Numeric(precision=14, scale=2), nullable=False, comment='Total taxable value before GST = quantity × unit_price'),
    sa.Column('gst_rate', sa.Integer(), nullable=False, comment='GST rate percentage: 5, 12, 18, or 28'),
    sa.Column('gst_amount', sa.Numeric(precision=14, scale=2), nullable=False, comment='Total GST charged — this is the ITC Ramesh can claim'),
    sa.Column('total_value', sa.Numeric(precision=14, scale=2), nullable=False, comment='Total invoice value including GST'),
    sa.Column('in_gstr2b', sa.Boolean(), nullable=False, comment='Whether this invoice appears in GSTR-2B — False means ITC at risk'),
    sa.Column('gstr2b_matched_at', sa.String(length=10), nullable=True, comment='Date when invoice appeared in GSTR-2B — NULL if not yet matched'),
    sa.Column('itc_eligible', sa.Boolean(), nullable=False, comment='Whether this purchase is eligible for ITC claim'),
    sa.Column('data_source', sa.String(length=20), nullable=False, comment='How this record entered the system: pdf_upload, tally_export, manual, gstn_api'),
    sa.Column('source_filename', sa.String(length=255), nullable=True, comment='Original filename if uploaded as PDF'),
    sa.Column('data_notes', sa.Text(), nullable=True, comment='Data quality notes — flags for manual review'),
    sa.Column('expected_delivery_date', sa.String(length=10), nullable=True, comment='Expected delivery date in YYYY-MM-DD format'),
    sa.Column('delivery_confirmed', sa.Boolean(), nullable=False, comment='Whether supplier has confirmed delivery'),
    sa.Column('delivery_received', sa.Boolean(), nullable=False, comment='Whether material has been physically received'),
    sa.Column('actual_delivery_date', sa.String(length=10), nullable=True, comment='Actual delivery date — for supplier reliability scoring'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchases_customer_id'), 'purchases', ['customer_id'], unique=False)
    op.create_index('ix_purchases_customer_period', 'purchases', ['customer_id', 'tax_period'], unique=False)
    op.create_index('ix_purchases_delivery', 'purchases', ['delivery_confirmed', 'expected_delivery_date'], unique=False)
    op.create_index(op.f('ix_purchases_material_name'), 'purchases', ['material_name'], unique=False)
    op.create_index('ix_purchases_material_period', 'purchases', ['material_name', 'tax_period'], unique=False)
    op.create_index(op.f('ix_purchases_supplier_gstin'), 'purchases', ['supplier_gstin'], unique=False)
    op.create_index(op.f('ix_purchases_tax_period'), 'purchases', ['tax_period'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchases_tax_period'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_supplier_gstin'), table_name='purchases')
    op.drop_index('ix_purchases_material_period', table_name='purchases')
    op.drop_index(op.f('ix_purchases_material_name'), table_name='purchases')
    op.drop_index('ix_purchases_delivery', table_name='purchases')
    op.drop_index('ix_purchases_customer_period', table_name='purchases')
    op.drop_index(op.f('ix_purchases_customer_id'), table_name='purchases')
    op.drop_table('purchases')
    op.drop_index('uq_itc_customer_period', table_name='itc_tracking')
    op.drop_index(op.f('ix_itc_tracking_customer_id'), table_name='itc_tracking')
    op.drop_index('ix_itc_status', table_name='itc_tracking')
    op.drop_table('itc_tracking')
    op.drop_index(op.f('ix_customers_gstin'), table_name='customers')
    op.drop_index(op.f('ix_customers_cluster'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
