"""fix last_reconciled_at column length

Revision ID: 5309fd1eaf9f
Revises: 2ca8972639d9
Create Date: 2026-09-05 20:41:07.335345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5309fd1eaf9f'
down_revision: Union[str, None] = '2ca8972639d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('itc_tracking', 'last_reconciled_at',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_comment='ISO datetime of last reconciliation run',
               existing_nullable=True)
    op.alter_column('itc_tracking', 'alert_sent_at',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_comment='ISO datetime when alert was sent to customer',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('itc_tracking', 'alert_sent_at',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_comment='ISO datetime when alert was sent to customer',
               existing_nullable=True)
    op.alter_column('itc_tracking', 'last_reconciled_at',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_comment='ISO datetime of last reconciliation run',
               existing_nullable=True)
    # ### end Alembic commands ###
