"""add payment_invoices table

Revision ID: 94ee5bbdfa18
Revises: 5309fd1eaf9f
Create Date: 2026-09-06 13:59:18.922501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94ee5bbdfa18'
down_revision: Union[str, None] = '5309fd1eaf9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_invoices',
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('buyer_name', sa.String(length=200), nullable=False, comment='Name of the customer who owes payment'),
    sa.Column('buyer_gstin', sa.String(length=15), nullable=True, comment='Buyer GSTIN for GST compliance'),
    sa.Column('buyer_phone', sa.String(length=15), nullable=True, comment='Buyer phone for automated payment reminders'),
    sa.Column('buyer_email', sa.String(length=255), nullable=True, comment='Buyer email for payment reminders'),
    sa.Column('invoice_number', sa.String(length=50), nullable=False, comment='Invoice number raised by Ramesh'),
    sa.Column('invoice_date', sa.String(length=10), nullable=False, comment='Invoice date YYYY-MM-DD'),
    sa.Column('due_date', sa.String(length=10), nullable=False, comment='Payment due date YYYY-MM-DD'),
    sa.Column('description', sa.Text(), nullable=True, comment='Description of goods/services supplied'),
    sa.Column('taxable_value', sa.Numeric(precision=14, scale=2), nullable=False, comment='Invoice value before GST'),
    sa.Column('gst_amount', sa.Numeric(precision=14, scale=2), nullable=False, comment='GST charged on this invoice'),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False, comment='Total invoice amount including GST'),
    sa.Column('amount_received', sa.Numeric(precision=14, scale=2), nullable=False, comment='Amount received so far'),
    sa.Column('is_paid', sa.Boolean(), nullable=False, comment='Whether invoice is fully paid'),
    sa.Column('paid_date', sa.String(length=10), nullable=True, comment='Date payment was received YYYY-MM-DD'),
    sa.Column('reminders_sent', sa.Integer(), nullable=False, comment='Number of payment reminders sent'),
    sa.Column('last_reminder_date', sa.String(length=10), nullable=True, comment='Date of last reminder sent'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Internal notes about payment status'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_invoices_customer_id'), 'payment_invoices', ['customer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_invoices_customer_id'), table_name='payment_invoices')
    op.drop_table('payment_invoices')
    # ### end Alembic commands ###
