"""add sales_invoices table

Revision ID: daa3b8fa1463
Revises: 94ee5bbdfa18
Create Date: 2026-09-06 15:07:05.748763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daa3b8fa1463'
down_revision: Union[str, None] = '94ee5bbdfa18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
