
# ==============================================================================
# PROCUREAI — integrations/sandbox_gst.py
# Client for Sandbox.co.in GST API.
#
# FRESHER EXPLANATION:
# This file is the "translator" between ProcureAI and the Indian
# government's GST portal (GSTN).
#
# GSTN is the government system that holds all GST data.
# It has an API but it's notoriously complex — requires encryption,
# OTP sessions, digital signatures.
#
# Sandbox.co.in is a company that handles all that complexity.
# They give us a simple REST API: "give me GSTR-2B for this GSTIN"
# and they return clean JSON.
#
# OUR JOB HERE:
# 1. Call Sandbox.co.in API correctly
# 2. Parse the response into our schema objects
# 3. Handle errors — API timeouts, invalid GSTIN, no data
# 4. Retry on temporary failures (rate limits, server errors)
#
# WHAT IS GSTR-2B?
# GSTR-2B is a monthly statement generated by GSTN on the 14th.
# It shows every purchase invoice where the SUPPLIER has filed
# their GSTR-1 (sales return). If a supplier hasn't filed,
# the invoice doesn't appear — and Ramesh loses that ITC.
# ==============================================================================

from decimal import Decimal
from typing import Optional

import httpx
from loguru import logger
from tenacity import (
    retry,
    retry_if_exception_type,
    stop_after_attempt,
    wait_exponential,
)

from procureai.config import get_settings
from procureai.schemas.purchase import MissingGSTR2BItem

settings = get_settings()


# ==============================================================================
# CUSTOM EXCEPTIONS
# Specific exceptions for GST API errors.
#
# FRESHER NOTE ON CUSTOM EXCEPTIONS:
# Python has built-in exceptions like ValueError, ConnectionError.
# But when the GSTN API returns "Invalid GSTIN", we want to raise
# something more specific than a generic Exception.
# Custom exceptions let callers handle specific errors differently:
#
# try:
#     data = await client.fetch_gstr2b(gstin, period)
# except InvalidGSTINError:
#     # This GSTIN is wrong — alert the CA to fix it
# except GSTNAPIError:
#     # GSTN is down — retry later
# except Exception:
#     # Something unexpected — log and investigate
# ==============================================================================

class GSTNAPIError(Exception):
    """Base exception for all GSTN API errors."""
    pass

class InvalidGSTINError(GSTNAPIError):
    """Raised when the GSTIN is invalid or not found in GSTN."""
    pass

class GSTNAuthError(GSTNAPIError):
    """Raised when Sandbox.co.in API key is invalid or expired."""
    pass

class GSTNDataNotAvailableError(GSTNAPIError):
    """
    Raised when GSTR-2B is not yet available for the requested period.
    This happens if you request before the 14th of the month.
    """
    pass

class GSTNRateLimitError(GSTNAPIError):
    """Raised when we've hit Sandbox.co.in's rate limit."""
    pass


# ==============================================================================
# GSTR-2B DATA CLASSES
# Clean Python objects representing GSTN data.
# These are NOT database models — they're temporary objects
# used during reconciliation, then discarded.
# ==============================================================================

class GSTR2BInvoice:
    """
    One invoice from GSTR-2B data.

    FRESHER NOTE:
    When GSTN returns GSTR-2B, it contains a list of invoices
    that suppliers have filed. Each invoice has:
    - Supplier GSTIN
    - Invoice number
    - Invoice date
    - Taxable value
    - GST amount

    We use this to cross-check against Ramesh's purchase invoices.
    If an invoice is in purchases but NOT in GSTR-2B → ITC at risk.
    """

    def __init__(
        self,
        supplier_gstin: str,
        invoice_number: str,
        invoice_date: str,
        taxable_value: Decimal,
        igst: Decimal,
        cgst: Decimal,
        sgst: Decimal,
    ):
        self.supplier_gstin = supplier_gstin.upper().strip()
        self.invoice_number = invoice_number.strip()
        self.invoice_date = invoice_date
        self.taxable_value = taxable_value

        # Total GST = IGST + CGST + SGST
        # For intra-state (Karnataka to Karnataka): CGST + SGST
        # For inter-state: IGST only
        # We sum all three — correct total regardless of transaction type
        self.total_gst = igst + cgst + sgst

    def __repr__(self) -> str:
        return (
            f"GSTR2BInvoice("
            f"supplier={self.supplier_gstin}, "
            f"inv={self.invoice_number}, "
            f"gst=₹{self.total_gst}"
            f")"
        )


class GSTR2BData:
    """
    Complete GSTR-2B data for one customer for one tax period.

    Contains all invoices filed by all suppliers for the period.
    The reconciliation service compares this against purchases.
    """

    def __init__(
        self,
        gstin: str,
        tax_period: str,
        invoices: list[GSTR2BInvoice],
        raw_response: dict,
    ):
        self.gstin = gstin
        self.tax_period = tax_period
        self.invoices = invoices
        self.raw_response = raw_response

        # Build a lookup set for fast matching
        # Key: (supplier_gstin, invoice_number) tuple
        # This lets us check "is this invoice in GSTR-2B?" in O(1) time
        # instead of looping through all invoices for every purchase
        self._invoice_keys = {
            (inv.supplier_gstin, inv.invoice_number.upper())
            for inv in invoices
        }

    def is_invoice_present(
        self, supplier_gstin: str, invoice_number: str
    ) -> bool:
        """
        Check if a specific invoice appears in GSTR-2B.

        FRESHER NOTE ON O(1) LOOKUP:
        If we had 500 invoices in GSTR-2B and 100 purchases to check,
        a naive loop would do 500 × 100 = 50,000 comparisons.
        A set lookup does 100 comparisons — one per purchase.
        Sets are implemented as hash tables — lookup is instant
        regardless of how many items are in the set.
        """
        key = (supplier_gstin.upper(), invoice_number.upper())
        return key in self._invoice_keys

    def get_invoice(
        self, supplier_gstin: str, invoice_number: str
    ) -> Optional[GSTR2BInvoice]:
        """
        Get a specific invoice from GSTR-2B data.
        Returns None if not found.
        """
        for inv in self.invoices:
            if (
                inv.supplier_gstin == supplier_gstin.upper()
                and inv.invoice_number.upper() == invoice_number.upper()
            ):
                return inv
        return None

    @property
    def total_invoices(self) -> int:
        return len(self.invoices)

    @property
    def unique_suppliers(self) -> set[str]:
        return {inv.supplier_gstin for inv in self.invoices}


# ==============================================================================
# SANDBOX GST CLIENT
# The main class that talks to Sandbox.co.in API
# ==============================================================================

class SandboxGSTClient:
    """
    HTTP client for Sandbox.co.in GST API.

    Usage:
        client = SandboxGSTClient()
        gstr2b = await client.fetch_gstr2b("29ABCDE1234F1Z5", "082026")
        is_present = gstr2b.is_invoice_present("29XYZ...", "INV-001")

    FRESHER NOTE ON ASYNC:
    All methods are async (await) because HTTP requests involve
    waiting for a remote server to respond.
    During that wait, Python can handle other requests.
    If we used sync HTTP (like the requests library), the entire
    application would freeze while waiting for GSTN to respond.
    httpx.AsyncClient is the async version of requests.
    """

    def __init__(self):
        self.base_url = settings.sandbox_base_url
        self.api_key = settings.sandbox_api_key
        self.timeout = settings.sandbox_timeout_seconds

    def _get_headers(self) -> dict:
        """
        Standard headers for all Sandbox.co.in API requests.

        FRESHER NOTE:
        Every HTTP request to Sandbox.co.in must include:
        - Authorization: our API key proves we're a registered client
        - x-api-key: same key in a different header (Sandbox requires both)
        - Content-Type: tells the server we're sending JSON
        """
        return {
            "Authorization": f"Bearer {self.api_key}",
            "x-api-key": self.api_key,
            "Content-Type": "application/json",
            "Accept": "application/json",
        }

    @retry(
        # Retry on network errors and rate limits
        retry=retry_if_exception_type((
            httpx.ConnectTimeout,
            httpx.ReadTimeout,
            GSTNRateLimitError,
        )),
        # Wait 1s, then 2s, then 4s between retries
        # This is "exponential backoff" — gives the server time to recover
        wait=wait_exponential(multiplier=1, min=1, max=10),
        # Maximum 3 attempts total
        stop=stop_after_attempt(3),
    )
    async def fetch_gstr2b(
        self, gstin: str, tax_period: str
    ) -> GSTR2BData:
        """
        Fetch GSTR-2B data for a customer for a specific tax period.

        Args:
            gstin: Customer's GSTIN e.g. "29ABCDE1234F1Z5"
            tax_period: Period in MMYYYY format e.g. "082026"

        Returns:
            GSTR2BData object with all filed invoices

        Raises:
            InvalidGSTINError: GSTIN not found in GSTN
            GSTNDataNotAvailableError: GSTR-2B not yet generated
            GSTNAuthError: API key invalid
            GSTNAPIError: Other GSTN errors
        """
        logger.info(
            f"Fetching GSTR-2B for GSTIN={gstin}, period={tax_period}"
        )

        # In development/testing without real API key,
        # return mock data so development can proceed
        if settings.sandbox_api_key == "your-sandbox-api-key":
            logger.warning(
                "Using mock GSTR-2B data — Sandbox API key not configured"
            )
            return self._get_mock_gstr2b(gstin, tax_period)

        async with httpx.AsyncClient(
            timeout=self.timeout
        ) as client:
            try:
                response = await client.get(
                    f"{self.base_url}/gst/gstr2b",
                    headers=self._get_headers(),
                    params={
                        "gstin": gstin,
                        "period": tax_period,
                    }
                )

                # Handle HTTP error responses
                self._handle_response_errors(response, gstin, tax_period)

                data = response.json()
                logger.info(
                    f"GSTR-2B fetched successfully for {gstin}: "
                    f"{len(data.get('invoices', []))} invoices"
                )

                return self._parse_gstr2b_response(
                    gstin, tax_period, data
                )

            except httpx.ConnectTimeout:
                logger.error(
                    f"GSTN API timeout for {gstin} period {tax_period}"
                )
                raise
            except httpx.RequestError as e:
                logger.error(f"GSTN API request error: {e}")
                raise GSTNAPIError(f"Network error: {e}")

    def _handle_response_errors(
        self,
        response: httpx.Response,
        gstin: str,
        tax_period: str,
    ) -> None:
        """
        Converts HTTP error responses to specific exceptions.

        FRESHER NOTE:
        HTTP status codes tell us what went wrong:
        200 = success
        400 = bad request (invalid GSTIN)
        401 = unauthorized (wrong API key)
        404 = not found (no GSTR-2B for this period yet)
        429 = too many requests (rate limited)
        500 = server error (GSTN is down)
        """
        if response.status_code == 200:
            return  # Success — no error

        error_body = {}
        try:
            error_body = response.json()
        except Exception:
            pass

        error_message = error_body.get("message", "Unknown error")

        if response.status_code == 401:
            raise GSTNAuthError(
                "Sandbox.co.in API key is invalid or expired. "
                "Check SANDBOX_API_KEY in environment variables."
            )

        if response.status_code == 400:
            raise InvalidGSTINError(
                f"Invalid GSTIN {gstin}: {error_message}"
            )

        if response.status_code == 404:
            raise GSTNDataNotAvailableError(
                f"GSTR-2B not available for {gstin} period {tax_period}. "
                "GSTR-2B is generated on the 14th of each month."
            )

        if response.status_code == 429:
            logger.warning("GSTN API rate limit hit — will retry")
            raise GSTNRateLimitError("Rate limit exceeded")

        # Any other error
        raise GSTNAPIError(
            f"GSTN API error {response.status_code}: {error_message}"
        )

    def _parse_gstr2b_response(
        self,
        gstin: str,
        tax_period: str,
        data: dict,
    ) -> GSTR2BData:
        """
        Parses Sandbox.co.in API response into GSTR2BData object.

        FRESHER NOTE:
        Raw API responses are messy nested JSON.
        This method extracts what we need and creates clean objects.
        We store the raw response too (for debugging) but work
        with clean objects in our business logic.
        """
        invoices = []

        # GSTN returns invoices under different keys depending on
        # the transaction type (B2B, CDNR, ISD etc.)
        # We only care about B2B invoices (business purchases)
        b2b_invoices = data.get("data", {}).get("b2b", [])

        for supplier in b2b_invoices:
            supplier_gstin = supplier.get("ctin", "")

            for invoice in supplier.get("inv", []):
                for item in invoice.get("itms", [{}]):
                    itm_det = item.get("itm_det", {})

                    try:
                        gstr2b_invoice = GSTR2BInvoice(
                            supplier_gstin=supplier_gstin,
                            invoice_number=invoice.get("inum", ""),
                            invoice_date=invoice.get("idt", ""),
                            taxable_value=Decimal(
                                str(itm_det.get("txval", 0))
                            ),
                            igst=Decimal(str(itm_det.get("iamt", 0))),
                            cgst=Decimal(str(itm_det.get("camt", 0))),
                            sgst=Decimal(str(itm_det.get("samt", 0))),
                        )
                        invoices.append(gstr2b_invoice)
                    except Exception as e:
                        logger.warning(
                            f"Could not parse invoice for {supplier_gstin}: {e}"
                        )
                        continue

        logger.info(
            f"Parsed {len(invoices)} B2B invoices from GSTR-2B "
            f"for {gstin} period {tax_period}"
        )

        return GSTR2BData(
            gstin=gstin,
            tax_period=tax_period,
            invoices=invoices,
            raw_response=data,
        )

    def _get_mock_gstr2b(
        self, gstin: str, tax_period: str
    ) -> GSTR2BData:
        """
        Returns realistic mock GSTR-2B data for development.

        FRESHER NOTE ON MOCK DATA:
        During development, we don't have real Sandbox.co.in
        API keys. Mock data lets us build and test the entire
        reconciliation flow without real credentials.

        The mock simulates a realistic scenario:
        - Sharma Metals filed correctly (invoice appears)
        - Kumar Tools did NOT file (invoice missing — ITC at risk)

        This lets us test that our alert correctly identifies
        Kumar Tools as the problem supplier.
        """
        logger.info(f"Returning mock GSTR-2B data for {gstin}")

        # Simulate: Sharma Metals filed their GSTR-1 correctly
        sharma_invoice = GSTR2BInvoice(
            supplier_gstin="29SHARMA1234F1Z5",
            invoice_number="INV-2846",
            invoice_date="2026-08-10",
            taxable_value=Decimal("56400.00"),
            igst=Decimal("0"),
            cgst=Decimal("5076.00"),
            sgst=Decimal("5076.00"),
        )

        # Kumar Tools is NOT in mock data — simulates they didn't file
        # Their invoice INV-1203 will be flagged as at risk

        return GSTR2BData(
            gstin=gstin,
            tax_period=tax_period,
            invoices=[sharma_invoice],
            raw_response={"mock": True, "period": tax_period},
        )


# ==============================================================================
# MODULE-LEVEL CLIENT INSTANCE
# One shared client for the entire application.
# Same pattern as get_settings() — created once, reused everywhere.
# ==============================================================================

gst_client = SandboxGSTClient()